add user
AnastasiyaYS/dualboot-task-manager pull request #10
Opened 2020-05-08 01:04 UTC by AnastasiyaYS

2020-05-08 10:32 UTC, mkalmykov requested changes

2020-05-08 10:32 UTC, mkalmykov commented on test/controllers/web/developers_controller_test.rb
> +    assert_response :redirect
Здесь тоже нужно протестировать суть операции создания пользователя.

2020-05-11 03:40 UTC, mkalmykov requested changes

2020-05-11 03:40 UTC, mkalmykov commented on test/controllers/web/developers_controller_test.rb
> +    assert :signed_in?
Этого недостаточно. Нужно проверить, что пользователь создался с ожидаемыми атрибутами.

2020-05-11 03:41 UTC, mkalmykov commented on test/controllers/web/developers_controller_test.rb
> +    assert :signed_in?
Кроме того, этот ассерт всегда будет проходить, даже если юзер не залогинен.

2020-05-11 18:50 UTC, pn-y requested changes

2020-05-11 18:50 UTC, pn-y commented on test/controllers/web/developers_controller_test.rb
> +    assert signed_in?
Идея понятно, но реализация - не совсем верная. 
Суть операции - в создании пользователя. 
Происходит сайнин после регистрации сразу или не происходит - побочный вопрос. 
Давай поменяем проверку, и проверим что после запроса появился девелопер с указанным нами емейлом.

2020-05-12 12:48 UTC, mkalmykov requested changes

2020-05-12 12:48 UTC, mkalmykov commented on test/controllers/web/developers_controller_test.rb
> +    assert_equal current_user.type, 'Developer'
Такая проверка не совсем корректна. Тест начнёт падать с неочевидной с первого взгляда ошибкой в случае, если мы перестанем логинить юзера после создания.

2020-05-12 12:48 UTC, mkalmykov commented on test/controllers/web/developers_controller_test.rb
> +    assert_equal Developer.last.email, email
`Developer.last` -- не очень надёжный способ поиска созданной записи. Он сломается, если по какой-то причине после регистрации будут созданы ещё девелоперы.

Для юзера первичным ключом служит email, уникальность которого валидируется, поэтому лучше воспользоваться методом `find_by` по этому полю и далее проверить, что юзер создался с правильными атрибутами (из `user_attributes`).

2020-05-12 19:15 UTC, pn-y approved these changes

2020-05-12 19:25 UTC, merged