Feature/kanban board
AnastasiyaYS/dualboot-task-manager pull request #15
Opened 2020-05-25 21:52 UTC by AnastasiyaYS

2020-05-25 21:59 UTC, AnastasiyaYS commented
Не получилось отрисовать доску с фейковыми данными после пункта 2, ошибки, которые были в консоли исправила, но доска так и не отобразилась(

2020-05-26 07:33 UTC, AnastasiyaYS commented
Я подключила в индекс таскборд, но доска тоже не появилась
`
import TaskBoard from './TaskBoard';
export default TaskBoard;
`

2020-05-26 20:51 UTC, pn-y requested changes

2020-05-26 20:51 UTC, pn-y commented on app/views/web/boards/show.html.slim
> +
Можно вообще удалить

2020-05-27 11:40 UTC, pn-y approved these changes

2020-05-27 15:56 UTC, merged