Feature/tasks
AnastasiyaYS/dualboot-task-manager pull request #18
Opened 2020-06-04 20:25 UTC by AnastasiyaYS

2020-06-05 12:07 UTC, pn-y requested changes

2020-06-05 12:07 UTC, pn-y commented on app/javascript/repositories/TasksRepository.js
> +  update(id, task = {}) {
Убери дефолтные параметры. Они могут скрывать собой ошибку

2020-06-06 19:06 UTC, helmq requested changes

2020-06-06 19:06 UTC, helmq commented on app/javascript/components/TaskBoard/TaskBoard.js
> +  const MODES = {
Константы лучше выносить из тела компонента.

2020-06-06 20:13 UTC, helmq approved these changes

2020-06-07 07:56 UTC, merged