generate models: User, Task, Developer, Manager, Admin
AnastasiyaYS/dualboot-task-manager pull request #5
Opened 2020-04-26 10:56 UTC by AnastasiyaYS

2020-04-27 09:00 UTC, pn-y requested changes

2020-04-27 09:00 UTC, pn-y commented on test/factories/tasks.rb
> +    author_id { 1 }
Не надо оперировать айдишниками, если есть возможность оперировать сущностями.
Не надо всегда создавать ассоциации - это приведет к неконтролируемому созданию сущностей по цепочке. Сделай их пустыми, и создай трейты для того создания автора или assignee.
Для создания остальных полей - используй sequence с алиасами, чтоб не приходилось каждый раз указывать какое-то-значение

2020-04-29 11:59 UTC, Andrew8xx8 commented
Пустые тесты надо удалить

2020-04-29 14:04 UTC, Andrew8xx8 approved these changes

2020-04-29 15:30 UTC, merged