Feature/task status
AnastasiyaYS/dualboot-task-manager pull request #7
Opened 2020-04-27 19:27 UTC by AnastasiyaYS

2020-04-28 12:24 UTC, pn-y requested changes

2020-04-28 12:24 UTC, pn-y commented on app/models/task.rb
> +            transition :new_task => :in_development
Перепиши на новый синтаксис хешей. Старый тут не нужен

2020-04-28 12:24 UTC, pn-y commented on app/models/task.rb
> +        event :to_develop do
Добавь список стейтов в самое начало стейт машины, чтоб было наглядно.
```
....
state :new_task
state :in_qa
...
```

2020-04-29 14:05 UTC, Andrew8xx8 requested changes

2020-04-29 14:05 UTC, Andrew8xx8 commented on app/models/task.rb
> +class Task < ActiveRecord::Base
Форматирование не верное в этом файле, запусти `rubocop`

2020-04-29 14:05 UTC, Andrew8xx8 commented on test/factories/tasks.rb
> +  factory :task do
Захардкоженная фабрика, тут скорее всего неактуальный код уже, нужно замержить предыдущие PR и сделать ребейз ветки

2020-04-29 14:05 UTC, Andrew8xx8 commented on test/factories/users.rb
> +  factory :user do
Захардкоженная фабрика, тут скорее всего неактуальный код уже, нужно замержить предыдущие PR и сделать ребейз ветки

2020-04-29 14:05 UTC, Andrew8xx8 commented on test/models/admin_test.rb
> +class AdminTest < ActiveSupport::TestCase
Пустые тесты удалить

2020-04-30 08:35 UTC, Andrew8xx8 approved these changes

2020-04-30 12:38 UTC, merged