Feature/reg and auth
AnastasiyaYS/dualboot-task-manager pull request #8
Opened 2020-05-06 16:23 UTC by AnastasiyaYS

2020-05-07 07:51 UTC, mkalmykov requested changes

2020-05-07 07:51 UTC, mkalmykov commented on app/javascript/packs/application.js
> +import 'material-design-lite/material.js';
Обычно рекомендуется настроить редактор так, чтобы при сохранении файла он вставлял пустую строку в конец.

2020-05-07 07:51 UTC, mkalmykov commented on app/javascript/packs/application.js
>  // const imagePath = (name) => images(name, true)
Закомментированный код лучше удалить.

2020-05-07 07:51 UTC, mkalmykov commented on config/application.rb
>      # the framework and any gems in your application.
Этот закомментированный код тоже не понадобится.

2020-05-07 07:51 UTC, mkalmykov commented on config/initializers/simple_form_materialize.rb
> +# Use this setup block to configure all options available in SimpleForm.
Комментарий не нужен. Если где-то в файлах ниже они ещё есть, надо тоже удалить.

2020-05-07 07:51 UTC, mkalmykov commented on config/initializers/simple_form_materialize.rb
> +  config.wrappers :materialize_form, tag: 'div', class: 'mdl-textfield mdl-js-textfield mdl-textfield--floating-label', error_class: 'is-invalid' do |b|
Рубокоп пропускает такую длинную строку? Попробуй применить автоформатирование.

2020-05-07 07:51 UTC, mkalmykov commented on test/controllers/web/application_controller_test.rb
> +class Web::ApplicationControllerTest < ActionDispatch::IntegrationTest
ApplicationController'ы обычно не тестируются, и оставлять пустые тесты нет смысла, можно просто удалить,

2020-05-07 07:51 UTC, mkalmykov commented on test/factories/admins.rb
> +    first_name { generate :string }
Сделай алиасы для сиквенса `string`.

2020-05-07 07:51 UTC, mkalmykov commented on test/factories/managers.rb
> +    email { generate :email }
Вместо трёх фабрик с одинаковыми атрибутами можно сделать одну фабрику `user`, и в ней вложенные фабрики для разных типов: https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#nested-factories

2020-05-07 07:51 UTC, mkalmykov commented on test/factories/tasks.rb
> +    state {}
Этот атрибут в фабрике не нужен -- его проинициализирует стейт-машина.

2020-05-07 07:51 UTC, mkalmykov commented on test/factories/users.rb
> +    type {}
Этот атрибут можно опустить. И в целом, если не использовать эту фабрику как базовую, отдельно она не имеет смысла.

2020-05-07 07:51 UTC, mkalmykov commented on test/factories/users.rb
> +    avatar {}
Необязательные поля в фабриках можно опускать.

2020-05-07 18:04 UTC, AnastasiyaYS commented on config/initializers/simple_form_materialize.rb
> +  config.wrappers :materialize_form, tag: 'div', class: 'mdl-textfield mdl-js-textfield mdl-textfield--floating-label', error_class: 'is-invalid' do |b|
Рубокоп поругался, но не исправил. Как красиво это отформатировать я даже не знаю.. Сделать переносы по запятым?

2020-05-07 18:39 UTC, mkalmykov commented on config/initializers/simple_form_materialize.rb
> +  config.wrappers :materialize_form, tag: 'div', class: 'mdl-textfield mdl-js-textfield mdl-textfield--floating-label', error_class: 'is-invalid' do |b|
да, возьми в скобки и перенеси по запятым:

```ruby
config.wrappers(
  :materialize_form,
  tag: 'div',
  class: 'mdl-textfield mdl-js-textfield mdl-textfield--floating-label',
  error_class: 'is-invalid',
)
```

2020-05-08 10:27 UTC, mkalmykov commented
Замечание общего плана -- применение рубокопа и выпил комментариев/ненужных файлов -- это хорошо, но лучше это делать сразу при инициализации нового проекта, иначе генерируется огромный дифф, который сложно смотреть и в котором теряются, собственно, изменения из фич.

Обычно, когда рубокоп добавляется в процессе разработки, изменения вносятся постепенно, только в затрагиваемых файлах и используется автогенерация конфига (`--auto-gen-config`).

Сейчас давай оставим PR как есть, с большим диффом, но на будущее нужно иметь в виду.

2020-05-08 10:28 UTC, mkalmykov requested changes

2020-05-08 10:28 UTC, mkalmykov commented on app/forms/session_form.rb
> +  validate :user_valid?
Давай попробуем дать этому методу более осмысленное название.

2020-05-08 10:28 UTC, mkalmykov commented on bin/bundle
> +require 'rubygems'
Бинстабы лучше не модифицировать. Это полностью автосгенерированный файл, модификации в который обычно никогда не вносятся. Лучше внести такие файлы в исключения рубокопа.

2020-05-08 10:28 UTC, mkalmykov commented on bin/bundle
> +require 'rubygems'
Комментарий относится к этому файлу и ко всем остальным бинстабам ниже.

2020-05-08 10:28 UTC, mkalmykov commented on db/schema.rb
> -# This file is auto-generated from the current state of the database. Instead
Этот файл полностью автогенерируемый и никогда не модифицируется руками. Нужно добавить в исключения рубокопа.

2020-05-08 10:28 UTC, mkalmykov commented on test/channels/application_cable/connection_test.rb
> -  # test "connects with cookies" do
Если в тесте ничего нет, можно его удалить.

2020-05-08 10:28 UTC, mkalmykov commented on test/controllers/web/application_controller_test.rb
> +class Web::ApplicationControllerTest < ActionDispatch::IntegrationTest
Не исправлено с прошлого ревью -- надо поправить.

2020-05-08 17:30 UTC, AnastasiyaYS commented on app/forms/session_form.rb
> +  validate :user_valid?
Не знаю, правильно ли я это поняла - если функции со знаком вопроса в руби должны возвращать булеан, а у нас возвращает nil, то нужно как-то так - user_check_validation ?

2020-05-08 18:03 UTC, AnastasiyaYS commented on bin/bundle
> +require 'rubygems'
Обновилось обучение и на ветку выше я уже добавила конфиг рубокопа, там всё есть)

2020-05-09 03:40 UTC, mkalmykov requested changes

2020-05-09 03:40 UTC, mkalmykov commented on app/forms/session_form.rb
> +  def user_check_validation
Думаю, в этом случае лучше назвать метод `check_credentials`.

2020-05-09 13:45 UTC, AnastasiyaYS commented on app/forms/session_form.rb
> +  def user_check_validation
Спасибо)

2020-05-09 17:20 UTC, Andrew8xx8 approved these changes

2020-05-09 18:01 UTC, mkalmykov approved these changes

2020-05-12 19:04 UTC, merged