Feature/reg and auth session
AnastasiyaYS/dualboot-task-manager pull request #9
Opened 2020-05-06 19:13 UTC by AnastasiyaYS

2020-05-07 07:32 UTC, mkalmykov commented
Изменения в этом PR дублируют изменения из #8. Сделай таргет-веткой этого PR ту, что в #8, чтобы можно было смотреть изменения изолированно. После вливания прошлого PR в develop поменяй таргет-ветку тут обратно на develop.

2020-05-08 10:31 UTC, mkalmykov requested changes

2020-05-08 10:31 UTC, mkalmykov commented on test/controllers/web/sessions_controller_test.rb
> +    assert_response :redirect
Здесь мы проверяем только статус-код ответа, но не проверяем бизнес-логику. Нужно протестировать ещё и суть операции. То же самое в тесте на `destroy`.

2020-05-08 10:31 UTC, mkalmykov commented on app/views/web/sessions/new.html.slim
> +    = f.button  :submit, "Sign in"
Прогони рубокоп. Есть ощущение, что будут правки, в том числе добавление пустой строки 🙁

2020-05-10 16:41 UTC, AnastasiyaYS commented on app/views/web/sessions/new.html.slim
> +    = f.button  :submit, "Sign in"
Рубокоп не проверяет файлы slim( Установить гем slim-lint?

2020-05-10 20:20 UTC, artempartos requested changes

2020-05-10 20:20 UTC, artempartos commented on test/controllers/web/sessions_controller_test.rb
> +    assert_response :redirect
куда редиректит проверять не обязательно, а что пользователь залогинен надо проверить

2020-05-10 20:21 UTC, artempartos commented
посмотри какие есть методы в auth_helper

2020-05-11 03:47 UTC, mkalmykov requested changes

2020-05-11 03:47 UTC, mkalmykov commented on app/views/web/sessions/new.html.slim
> +    = f.button  :submit, "Sign in"
Не надо. Сконфигурируй редактор, чтобы он вставлял пустую строку в конце файла.

2020-05-11 03:47 UTC, mkalmykov commented on test/controllers/web/sessions_controller_test.rb
> +    assert :signed_in?
Этот ассерт всегда будет проходить, даже если юзер не залогинен, потому что сам метод здесь не вызывается.

2020-05-11 03:47 UTC, mkalmykov commented on test/controllers/web/sessions_controller_test.rb
> +    assert_nil session[:user_id]
Не нужно взаимодействовать с сессией напрямую. Воспользуйся методом из auth_helper.

2020-05-11 03:47 UTC, mkalmykov commented on app/views/web/sessions/new.html.slim
>  p Find me in app/views/web/sessions/new.html.slim
Раз тут добавляется код формы, вероятно, строки 1 и 2 больше не нужны.

2020-05-11 18:48 UTC, pn-y approved these changes

2020-05-12 19:06 UTC, merged